# Dockerfile da API algafood-api
version: "3.9"

# Rede
networks:
  algafood-network:
    driver: bridge

# Serviços (cada container que se quer levantar)
services:

  # MySQL
  algafood-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - algafood-network
      
  # API
  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql

  # PROXY Reverso feito com o nginx
  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api