# Dockerfile da API algafood-api
version: "3.9"

# Rede
networks:
  algafood-network:
    driver: bridge

# Serviços (cada container que se quer levantar)
services:

  # MySQL
  algafood-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - algafood-network
      
  # API
  algafood-api:
    image: algafood-api
    environment:
      DB_HOST: algafood-mysql
    ports:
      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql
      